# Upstream's switched-off bundles (OPTIONAL_BUNDLES): resolvable for every
# profile, selected by none. Generated by scripts/generate-optional-bundles.sh
# into pkgs/dsh-workspace/optional-bundles.json, so this file stays fixed.
{
  lib,
  buildDshBundle,
  dsh-kernel,
  dsh-workspace,
}:
let
  manifest = lib.importJSON ../pkgs/dsh-workspace/optional-bundles.json;

  mkBundle =
    packageName: entry:
    buildDshBundle.fromWorkspace (_finalAttrs: {
      inherit dsh-kernel dsh-workspace packageName;

      inherit (entry) pname;

      linkKernelNodeModules = dsh-kernel;

      passthru = lib.optionalAttrs entry.requiresWeb {
        requiresWeb = true;
      };

      meta = {
        inherit (entry) description;
        descriptions.zh-CN = entry.descriptionZh;
        homepage = "https://github.com/deepseek-ai/deepseek-harness";
        license = lib.licenses.mit;
        platforms = lib.platforms.unix;
      };
    });
in
lib.mapAttrs' (
  packageName: entry: lib.nameValuePair entry.attr (mkBundle packageName entry)
) manifest
