#!/usr/bin/env bash
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
docs_dir="$repo_root/docs"
tmp_dir=$(mktemp -d)
check_mode=0
locales=()

cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check)
      check_mode=1
      ;;
    --lang)
      shift
      case "${1:-}" in
        en)
          locales=(en)
          ;;
        zh-CN)
          locales=(zh-CN)
          ;;
        *)
          echo "unsupported locale: ${1:-}; expected en or zh-CN" >&2
          exit 1
          ;;
      esac
      ;;
    *)
      echo "usage: generate-docs [--check] [--lang en|zh-CN]" >&2
      exit 1
      ;;
  esac
  shift
done

if [ "${#locales[@]}" -eq 0 ]; then
  locales=(en zh-CN)
fi

catalog=$(
  # shellcheck disable=SC2016
  nix eval --impure --json --expr '
    let
      repo = toString ./.;
      flake = builtins.getFlake repo;
      system = builtins.currentSystem;
      scope = flake.legacyPackages.${system};
    in
    import ./lib/catalog.nix { inherit scope; }
  '
)

mkdir -p "$docs_dir"

render_en() {
  local output=$1

  {
    cat <<'EOF'
# Bundles and Presets

This catalog is generated from the flake. Do not edit this file by hand.

Bundles are plugin-style extensions. Pick the ones you need and combine them
into your own setup in order; later bundles override earlier Cordis
configuration. For example, add bundles to an existing preset with
`pkgs.dsh.presets.web-ui.override { extraPlugins = [ pkgs.dsh.bundles.tui ]; }`,
or declare a custom profile with `programs.dsh.profiles.mine.bundles = [ ... ]`.
See the [README](../README.en.md) for details.

## Bundles

| Flake output | Package | Version | Description |
|---|---|---|---|
EOF
    jq -r '
      .bundles[] |
      "| `bundles.\(.name)` | `\(.package)` | \(.version // "-") | \(.description // "-" | gsub("[|]"; "\\|"))\(if .homepage then " · [homepage](\(.homepage))" else "" end) |"
    ' <<<"$catalog"
    cat <<'EOF'

## Presets

| Flake output | Default profile | Bundles | Description |
|---|---|---|---|
EOF
    jq -r '
      .presets[] |
      "| `presets.\(.name)` | \(if .defaultProfile then "`\(.defaultProfile)`" else "-" end) | \([.bundles[] | "`" + . + "`"] | join(", ")) | \(.description // "-" | gsub("[|]"; "\\|"))\(if .homepage then " · [homepage](\(.homepage))" else "" end) |"
    ' <<<"$catalog"
  } > "$output"
}

render_zh() {
  local output=$1

  {
    cat <<'EOF'
# Bundles 和预设

本目录由 flake 自动生成，仅作参考。请勿手工编辑。

Bundle 即插件式扩展。按顺序拼接需要的 bundle，就能得到自己的组合；后面的
bundle 会覆盖前面的 Cordis 配置。例如给已有 preset 追加 bundle：
`pkgs.dsh.presets.web-ui.override { extraPlugins = [ pkgs.dsh.bundles.tui ]; }`；
或在 NixOS 中自定义 profile：`programs.dsh.profiles.mine.bundles = [ ... ]`。
详见 [README](../README.md)。

## Bundles

| Flake 输出 | 包 | 版本 | 说明 |
|---|---|---|---|
EOF
    jq -r '
      .bundles[] |
      "| `bundles.\(.name)` | `\(.package)` | \(.version // "-") | \(.descriptionZh // "-" | gsub("[|]"; "\\|"))\(if .homepage then " · [主页](\(.homepage))" else "" end) |"
    ' <<<"$catalog"
    cat <<'EOF'

## 预设

| Flake 输出 | 默认 profile | Bundles | 说明 |
|---|---|---|---|
EOF
    jq -r '
      .presets[] |
      "| `presets.\(.name)` | \(if .defaultProfile then "`\(.defaultProfile)`" else "-" end) | \([.bundles[] | "`" + . + "`"] | join(", ")) | \(.descriptionZh // "-" | gsub("[|]"; "\\|"))\(if .homepage then " · [主页](\(.homepage))" else "" end) |"
    ' <<<"$catalog"
  } > "$output"
}

render() {
  local locale=$1
  local output=$2
  local tmp_file
  tmp_file="$tmp_dir/$(basename "$output")"

  if [ "$locale" = "zh-CN" ]; then
    render_zh "$tmp_file"
  else
    render_en "$tmp_file"
  fi

  prettier --parser markdown --write "$tmp_file" >/dev/null

  if [ "$check_mode" -eq 1 ]; then
    if ! diff -u "$output" "$tmp_file"; then
      echo "$output is stale; run: nix run .#generate-docs" >&2
      exit 1
    fi
  else
    mv "$tmp_file" "$output"
    echo "updated $output"
  fi
}

for locale in "${locales[@]}"; do
  if [ "$locale" = "zh-CN" ]; then
    render zh-CN "$docs_dir/bundles-presets.zh-CN.md"
  else
    render en "$docs_dir/bundles-presets.md"
  fi
done
